# Site Settings
m:
  dev_mode: true # do not change unless you know what you are doing
  syntax: "·" # syntax
  opacity: "0.87" # card opacity
  border_radius: "4px" # card border-radius
  max_width: "720px" # container max width
  layout: "dark" # appbar/drawer layout, light / dark / auto
  # https://pximg.kwaa.moe/img-original/img/2017/01/23/23/51/08/61082386_p0.jpg
  css: |
    body{background:url("https://i.loli.net/2020/08/04/oKlCG1pSxjb2hwT.jpg"), rgba(0,0,0,.39);background-repeat:no-repeat;background-position:center center;background-size:cover;background-attachment:fixed;background-blend-mode:multiply;}
    code[class*=language-],pre[class*=language-]{text-align:left;white-space:pre;word-spacing:normal;word-break:normal;word-wrap:normal;color:#eee!important;background:#2f2f2f!important;font-family:'Source Code Pro','Roboto Mono',Consolas,Menlo,monospace,sans-serif!important;font-size:1em;line-height:1.5em;-moz-tab-size:4;-o-tab-size:4;tab-size:4;-webkit-hyphens:none;-moz-hyphens:none;-ms-hyphens:none;hyphens:none}code[class*=language-] ::-moz-selection,code[class*=language-]::-moz-selection,pre[class*=language-] ::-moz-selection,pre[class*=language-]::-moz-selection{background:#363636}code[class*=language-] ::selection,code[class*=language-]::selection,pre[class*=language-] ::selection,pre[class*=language-]::selection{background:#363636!important}:not(pre)>code[class*=language-]{white-space:normal;border-radius:.2em;padding:.1em}pre[class*=language-]{overflow:auto;position:relative;margin:.5em 0;padding:1.25em 1em}.language-css>code,.language-sass>code,.language-scss>code{color:#fd9170!important}[class*=language-] .namespace{opacity:.7}.token.atrule{color:#c792ea!important}.token.attr-name{color:#ffcb6b!important}.token.attr-value{color:#a5e844!important}.token.attribute{color:#a5e844!important}.token.boolean{color:#c792ea!important}.token.builtin{color:#ffcb6b!important}.token.cdata{color:#80cbc4!important}.token.char{color:#80cbc4!important}.token.class{color:#ffcb6b!important}.token.class-name{color:#f2ff00!important}.token.comment{color:#616161!important}.token.constant{color:#c792ea!important}.token.deleted{color:#f66!important}.token.doctype{color:#616161!important}.token.entity{color:#f66!important}.token.function{color:#c792ea!important}.token.hexcode{color:#f2ff00!important}.token.id{color:#c792ea!important}.token.important{color:#c792ea!important}.token.inserted{color:#80cbc4!important}.token.keyword{color:#c792ea!important}.token.number{color:#fd9170!important}.token.operator{color:#89ddff!important}.token.prolog{color:#616161!important}.token.property{color:#80cbc4!important}.token.pseudo-class{color:#a5e844!important}.token.pseudo-element{color:#a5e844!important}.token.punctuation{color:#89ddff!important}.token.regex{color:#f2ff00!important}.token.selector{color:#f66!important}.token.string{color:#a5e844!important}.token.symbol{color:#c792ea!important}.token.tag{color:#f66!important}.token.unit{color:#fd9170!important}.token.url{color:#f66!important}.token.variable{color:#f66!important}
  init: |

mdui:
  primary: "blue" # https://mdui.org/docs/color
  accent: "blue" # https://mdui.org/docs/color
  layout: "auto" # card layout, light / dark / auto
  shadow: "0" # card shadow, 0-16
  hoverable: true # card hoverable, false / true
  card_media_covered: gradient # card media covered, normal / gradient / transparent 
  drawer_close: true # false / true

head:
  theme_color: "#2196F3"
  favicon: # 16*16 / 32*32 / 48*48
  high_res_icon: # 192*192
  apple_touch_icon: # 180*180
  preload:
    - 'href="https://cdn.jsdelivr.net/npm/mdui@1.0.0/dist/icons/material-icons/MaterialIcons-Regular.woff2" as="font" crossorigin'
    - 'href="https://cdn.jsdelivr.net/npm/mdui@1.0.0/dist/fonts/roboto/Roboto-Medium.woff2" as="font" crossorigin'
    - 'href="https://cdn.jsdelivr.net/npm/mdui@1.0.0/dist/fonts/roboto/Roboto-Regular.woff2" as="font" crossorigin'
    - 'href="https://cdn.jsdelivr.net/npm/mdui@1.0.0/dist/fonts/roboto/Roboto-Bold.woff2" as="font" crossorigin'
  preconnect:
    - 'href="//cdn.jsdelivr.net"'
    - 'href="//i.loli.net"'
  prefetch:
  dns_prefetch:
  stylesheet:

url:
  rss: "/atom.xml"
  avatar: "/about/"
  search: "/search/"
  links: "/links/"
  hosted_on: "https://github.com/kwaa/kwaa.github.io"

appbar:
  scroll_hide: true
  title: true
  search: true
  rss: false

drawer:
  avatar: "https://i.loli.net/2020/08/03/48LIyAOVr32tChe.png"
  toc: true
  search: false
  home: true
  archives: true
  categories: true
  tags: true
  links: true
  rss: false
  custom:
    "Google":
      class: "material-icons"
      content: "search"
      url: "https://google.com"

footer:
  since: "2019"
  hosted_on: "Github"
  powered_by_hexo: true
  theme_m: true
  custom: |
    <a href="https://kwaa.dev/atom.xml">RSS</a> | BG: <a href="https://www.pixiv.net/artworks/61082386">星の唄</a>

open_graph:
  google_analytics:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:

posts:
  thumbnail_title: false # true /false
  index_content: auto # false / auto / excerpt / content
  show_categories: false
  license: '<a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>'

comments:
  use: utterances # utterances
  utterances:
    repo: kwaa/comments
    issue_term: pathname
    theme: github-light
    src: "https://utteranc.es/client.js"

search:
  use: google # google
  google:
    search_site: "kwaa.dev"

plugins:
  pjax: true
  pangu: false
  script:

vendors:
  mdui_css: "https://cdn.jsdelivr.net/npm/mdui@1.0.0/dist/css/mdui.min.css" # 1.0.0
  mdui_js: "https://cdn.jsdelivr.net/npm/mdui@1.0.0/dist/js/mdui.min.js" # 1.0.0
  pjax_js: "https://cdn.jsdelivr.net/npm/pjax/pjax.min.js"
  pangu_js: "https://cdn.jsdelivr.net/npm/pangu@4.0.7/dist/browser/pangu.min.js" # 4.0.7
  prism_js: "https://cdn.jsdelivr.net/npm/prismjs@1.20.0/prism.min.js" # 1.2.0
  prism_theme: "https://cdn.jsdelivr.net/gh/PrismJS/prism-themes/themes/prism-material-dark.min.css"
  busuanzi_js: "https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js" # 2.3